# Generated by Django 5.0 on 2024-01-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brigadas', '0010_alter_articuloinventario_ubicacion'),
        ('clientes', '0018_rename_mbps_cliente_mbps_f_cliente_mbps_w'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('materiales', models.CharField(max_length=1000, null=True)),
                ('instalado', models.BooleanField(default=False)),
                ('brigada', models.ManyToManyField(to='brigadas.brigada')),
                ('cliente', models.ManyToManyField(to='clientes.cliente')),
            ],
            options={
                'db_table': 'instalaciones',
            },
        ),
    ]
