# Generated by Django 5.0 on 2024-02-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0006_alter_instalacion_brigada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalacion',
            name='brigada',
        ),
    ]
