# Generated by Django 5.0 on 2024-02-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0007_remove_instalacion_brigada'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='brigada',
            field=models.IntegerField(null=True),
        ),
    ]
