# Generated by Django 5.0 on 2024-02-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0010_alter_instalacion_brigada'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='nota',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
