# Generated by Django 5.0 on 2023-12-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='empleados',
        ),
    ]
