# Generated by Django 5.0 on 2023-12-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_empleado_options_remove_empleado_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
