# Generated by Django 5.0 on 2023-12-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
