# Generated by Django 5.0 on 2023-12-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_registrouso'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('brigadas', '0002_remove_tecnico_nombre_tecnico_usuario_and_more'),
        ('empleados', '0005_alter_empleado_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empleado',
            new_name='Empleados',
        ),
    ]
