# Generated by Django 5.0 on 2023-12-10 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brigada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ficha', models.CharField(max_length=3)),
                ('placa', models.CharField(max_length=10)),
                ('inventario', models.ManyToManyField(to='almacen.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brigadas.brigada')),
            ],
        ),
    ]
