# Generated by Django 5.0 on 2023-12-27 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brigadas', '0001_initial'),
        ('empleados', '0002_empleado_telefono_alter_empleado_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico',
            name='nombre',
        ),
        migrations.AddField(
            model_name='tecnico',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='brigada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brigadas.brigada'),
        ),
    ]
