# Generated by Django 5.0 on 2023-12-30 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brigadas', '0003_brigada_lider_delete_tecnico'),
        ('empleados', '0006_rename_empleado_empleados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brigada',
            name='lider',
        ),
        migrations.AlterField(
            model_name='brigada',
            name='placa',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='brigada',
            name='lider',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lider', to='empleados.empleados'),
        ),
    ]
