# Generated by Django 5.0 on 2023-12-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0008_remove_almacenbrigada_brigada_and_more'),
        ('brigadas', '0004_remove_brigada_lider_alter_brigada_placa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brigada',
            name='inventario',
        ),
        migrations.AddField(
            model_name='brigada',
            name='articulos',
            field=models.ManyToManyField(to='almacen.almacenbrigada'),
        ),
    ]
