# Generated by Django 5.0 on 2023-12-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brigadas', '0005_remove_brigada_inventario_brigada_articulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='articuloInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=50, null=True)),
                ('cantidad', models.IntegerField(null=True)),
                ('medida', models.CharField(max_length=20, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='brigadaInventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('articulos', models.ManyToManyField(to='brigadas.articuloinventario')),
            ],
        ),
        migrations.AlterField(
            model_name='brigada',
            name='articulos',
            field=models.ManyToManyField(to='brigadas.brigadainventario'),
        ),
    ]
