# Generated by Django 5.0 on 2023-12-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brigadas', '0006_articuloinventario_brigadainventario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articuloinventario',
            name='ubicacion',
            field=models.IntegerField(null=True),
        ),
    ]
