# Generated by Django 5.0 on 2024-01-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brigadas', '0007_articuloinventario_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articuloinventario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
