# Generated by Django 5.0 on 2024-01-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brigadas', '0008_alter_articuloinventario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brigada',
            name='lider',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
