# Generated by Django 5.0 on 2023-12-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('mac', models.CharField(max_length=50)),
                ('emisor', models.CharField(max_length=50)),
                ('ppp', models.CharField(blank=True, max_length=50, null=True)),
                ('c_nap', models.CharField(max_length=50, null=True)),
                ('ubicacion', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
