# Generated by Django 5.0 on 2023-12-10 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_c_nap_alter_cliente_emisor_and_more'),
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='c_instalado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='router',
            name='instalado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='router',
            name='emisor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='ip',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='mac',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='marca',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='router',
            name='ppp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='ubicacion',
            field=models.CharField(choices=[('ap', 'Almacen Principal'), ('f1', 'Ficha 1'), ('f2', 'Ficha 2'), ('f3', 'Ficha 3'), ('f4', 'Ficha 4'), ('f5', 'Ficha 5'), ('f6', 'Ficha 6'), ('f7', 'Ficha 7'), ('cliente', 'Cliente')], max_length=50, null=True),
        ),
    ]
