# Generated by Django 5.0 on 2023-12-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_router_c_instalado_router_instalado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='router',
            old_name='c_nap',
            new_name='clave',
        ),
        migrations.RenameField(
            model_name='router',
            old_name='emisor',
            new_name='pass_wifi',
        ),
        migrations.RenameField(
            model_name='router',
            old_name='ppp',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='router',
            name='ip',
        ),
        migrations.AddField(
            model_name='router',
            name='fecha_instalado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='ubicacion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
