# Generated by Django 5.0 on 2023-12-27 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_remove_cliente_ip_cliente_ip_activo'),
        ('equipos', '0003_rename_c_nap_router_clave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50)),
                ('mac', models.CharField(max_length=50, null=True)),
                ('pass_wifi', models.CharField(max_length=50, null=True)),
                ('clave', models.CharField(max_length=50, null=True)),
                ('usuario', models.CharField(max_length=50, null=True)),
                ('ubicacion', models.CharField(default='Almacen', max_length=50)),
                ('instalado', models.BooleanField(default=False)),
                ('fecha_instalado', models.DateField(blank=True, null=True)),
                ('c_instalado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Router',
        ),
    ]
