# Generated by Django 5.0 on 2024-02-13 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brigadas', '0011_remove_brigadainventario_articulos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='usoBrigada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('articulos_usados', models.TextField(max_length=1000, null=True)),
                ('cliente', models.CharField(max_length=100, null=True)),
                ('brigada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brigadas.brigada')),
            ],
            options={
                'verbose_name': 'Uso',
                'verbose_name_plural': 'Usos',
                'db_table': 'uso',
            },
        ),
    ]
