# Generated by Django 5.0 on 2024-02-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usobrigada',
            name='razon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
