# Generated by Django 5.0 on 2023-12-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('plan', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('res', 'Residencial'), ('emp', 'Empresarial')], max_length=100)),
                ('ppp', models.CharField(max_length=50)),
                ('c_nap', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('mac', models.CharField(max_length=50)),
                ('emisor', models.CharField(max_length=50)),
            ],
        ),
    ]
