# Generated by Django 5.0 on 2023-12-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_c_nap_alter_cliente_emisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='name',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='zona',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('res', 'Residencial'), ('emp', 'Empresarial'), ('inst', 'Institucional')], max_length=100),
        ),
    ]
