# Generated by Django 5.0 on 2023-12-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_cliente_address_remove_cliente_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='f_reg',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='clientes',
        ),
    ]
