# Generated by Django 5.0 on 2023-12-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_cedula_alter_cliente_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='f_nac',
            field=models.DateField(null=True),
        ),
    ]
