# Generated by Django 5.0 on 2023-12-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_f_nac'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rnc',
            field=models.IntegerField(null=True),
        ),
    ]
