# Generated by Django 5.0 on 2023-12-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_cliente_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='instalado',
            field=models.BooleanField(default=False),
        ),
    ]
