# Generated by Django 5.0 on 2023-12-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_cliente_instalado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='instalado',
            field=models.DateTimeField(null=True),
        ),
    ]
