# Generated by Django 5.0 on 2023-12-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_alter_cliente_instalado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='f_reg',
        ),
        migrations.AddField(
            model_name='cliente',
            name='mbps',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
