# Generated by Django 5.0 on 2023-12-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_remove_cliente_f_reg_cliente_mbps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='f_reg',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
