# Generated by Django 5.0 on 2023-12-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_remove_cliente_ip_cliente_ip_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='mbps',
            new_name='mbps_f',
        ),
        migrations.AddField(
            model_name='cliente',
            name='mbps_w',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
