# Generated by Django 5.0 on 2023-12-10 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brigadas', '0001_initial'),
        ('clientes', '0002_alter_cliente_c_nap_alter_cliente_emisor_and_more'),
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='brigada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brigadas.brigada'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
