# Generated by Django 5.0 on 2023-12-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0002_alter_ticket_brigada_alter_ticket_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
