# Generated by Django 5.0 on 2023-12-26 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brigadas', '0001_initial'),
        ('clientes', '0014_cliente_bajada_cliente_subida'),
        ('soporte', '0003_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('descripcion', models.TextField(max_length=1000, null=True)),
                ('estado', models.CharField(max_length=50, null=True)),
                ('solucion', models.TextField(max_length=1000, null=True)),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brigadas.brigada')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
    ]
