# Generated by Django 5.0 on 2023-12-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='fecha',
            new_name='f_reg',
        ),
        migrations.AddField(
            model_name='ticket',
            name='f_compromiso',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='prioridad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='titulo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
