# Generated by Django 5.0 on 2024-01-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0005_rename_fecha_ticket_f_reg_ticket_f_compromiso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='prioridad',
            field=models.CharField(default='Regular', max_length=50),
        ),
    ]
