# Generated by Django 5.0 on 2024-01-09 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brigadas', '0007_articuloinventario_ubicacion'),
        ('soporte', '0006_alter_ticket_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='brigada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brigadas.brigada'),
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.TextField(max_length=1000, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.ticket')),
            ],
            options={
                'db_table': 'notas',
            },
        ),
    ]
