# Generated by Django 5.0 on 2024-01-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0007_alter_ticket_brigada_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='estado',
        ),
        migrations.AddField(
            model_name='ticket',
            name='solucionado',
            field=models.BooleanField(default=False),
        ),
    ]
