# Generated by Django 5.0 on 2024-01-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0008_remove_ticket_estado_ticket_solucionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='nota',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Notas',
        ),
    ]
