# Generated by Django 5.0 on 2023-12-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('costo', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('medida', models.CharField(choices=[('m', 'metros'), ('cm', 'centimetros'), ('mm', 'milimetros'), ('kg', 'kilogramos'), ('g', 'gramos'), ('l', 'litros'), ('ml', 'mililitros')], max_length=20)),
            ],
        ),
    ]
