# Generated by Django 5.0 on 2023-12-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='medida',
            field=models.CharField(choices=[('ud', 'unidades'), ('m', 'metros'), ('cm', 'centimetros'), ('mm', 'milimetros'), ('kg', 'kilogramos'), ('g', 'gramos'), ('l', 'litros'), ('ml', 'mililitros')], default='ud', max_length=20),
        ),
    ]
