# Generated by Django 5.0 on 2023-12-30 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0007_almacenbrigada'),
        ('empleados', '0006_rename_empleado_empleados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacenbrigada',
            name='brigada',
        ),
        migrations.RemoveField(
            model_name='almacenbrigada',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='almacenbrigada',
            name='inventario',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='fecha_actualizacion',
        ),
        migrations.AddField(
            model_name='almacenbrigada',
            name='articulo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='almacenbrigada',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='almacenbrigada',
            name='encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encargado', to='empleados.empleados'),
        ),
        migrations.AddField(
            model_name='almacenbrigada',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='almacenbrigada',
            name='medida',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='fecha_salida',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='medida',
            field=models.CharField(default='Unidad', max_length=20),
        ),
    ]
