# Generated by Django 5.0 on 2023-12-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0009_alter_almacenbrigada_table_delete_registrouso'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='almacenbrigada',
            table=None,
        ),
    ]
