# Generated by Django 5.0 on 2023-12-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0011_alter_almacenbrigada_medida_alter_articulo_medida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacenbrigada',
            name='medida',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
