# Generated by Django 5.0 on 2023-12-30 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0012_alter_almacenbrigada_medida_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroUso',
        ),
    ]
