# Generated by Django 5.0 on 2023-12-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0013_delete_registrouso'),
        ('brigadas', '0006_articuloinventario_brigadainventario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='almacenBrigada',
        ),
    ]
