# Generated by Django 5.0 on 2024-02-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0014_delete_almacenbrigada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='ubicacion',
        ),
    ]
