# Generated by Django 5.0 on 2023-12-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0002_rename_is_active_ip_activo_ip_usadopor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ip',
            old_name='usadopor',
            new_name='usedby',
        ),
    ]
