# Generated by Django 5.0 on 2023-12-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0003_rename_usadopor_ip_usedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
