# Generated by Django 5.0 on 2023-12-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0004_alter_ip_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
